//
//  OpenAIResponse.swift
//  AIProxy
//
//  Created by Lou Zell on 3/13/25.
//

/// https://platform.openai.com/docs/api-reference/responses/object
// Implementor's note:
// See 'class Response' in `src/openai/types/responses/response.py `
public struct OpenAIResponse: Decodable {
    /// Unix timestamp (in seconds) of when this Response was created.
    public let createdAt: Double?

    /// An error object returned when the model fails to generate a Response.
    public let error: ResponseError?

    /// Unique identifier for this Response.
    public let id: String?

    /// Details about why the response is incomplete.
    public let incompleteDetails: IncompleteDetails?

    /// Inserts a system (or developer) message as the first item in the model's context.
    /// When using along with `previousResponseId`, the instructions from a previous response will not be carried over to the next response.
    /// This makes it simple to swap out system (or developer) messages in new responses.
    public let instructions: String?

    /// An upper bound for the number of tokens that can be generated for a response, including visible output tokens and [reasoning tokens](https://platform.openai.com/docs/guides/reasoning).
    public let maxOutputTokens: Int?

    /// Set of 16 key-value pairs that can be attached to an object.
    /// This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard.
    /// Keys are strings with a maximum length of 64 characters.
    /// Values are strings with a maximum length of 512 characters.
    public let metadata: [String: String]?

    /// Model ID used to generate the response, like `gpt-4o` or `o1`.
    /// OpenAI offers a wide range of models with different capabilities, performance characteristics, and price points.
    /// Refer to the [model guide](https://platform.openai.com/docs/models) to browse and compare available models.
    public let model: String?

    /// An array of content items generated by the model.
    /// - The length and order of items in the `output` array is dependent on the model's response.
    /// - Rather than accessing the first item in the `output` array and assuming it's an `assistant` message with the content generated by the model, you might consider using the `outputText` getter.
    public let output: [ResponseOutputItem]

    /// Whether to allow the model to run tool calls in parallel.
    public let parallelToolCalls: Bool?

    /// The unique ID of the previous response to the model.
    /// Use this to create multi-turn conversations.
    /// Learn more about [conversation state](https://platform.openai.com/docs/guides/conversation-state).
    public let previousResponseId: String?

    /// o-series models only
    /// Configuration options for [reasoning models](https://platform.openai.com/docs/guides/reasoning).
    public let reasoning: Reasoning?

    /// The status of the response generation.
    /// One of `completed`, `failed`, `in_progress`, or `incomplete`.
    public let status: Status?

    /// Configuration options for a text response from the model.
    /// Can be plain text or structured JSON data.
    /// Learn more:
    /// - [Text inputs and outputs](https://platform.openai.com/docs/guides/text)
    /// - [Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs)
    public let text: ResponseTextConfig?

    /// What sampling temperature to use, between 0 and 2.
    /// Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
    /// We generally recommend altering this or `topP` but not both.
    public let temperature: Double?

    /// How the model should select which tool (or tools) to use when generating a response.
    /// See the `toolChoice` parameter to see how to specify which tools the model can call.
    public let toolChoice: ToolChoice?

    /// An array of tools the model may call while generating a response.
    /// You can specify which tool to use by setting the `toolChoice` parameter.
    /// The two categories of tools you can provide the model are:
    /// - **Built-in tools**: Tools that are provided by OpenAI that extend the model's capabilities, like [web search](https://platform.openai.com/docs/guides/tools-web-search) or [file search](https://platform.openai.com/docs/guides/tools-file-search).
    ///   Learn more about [built-in tools](https://platform.openai.com/docs/guides/tools).
    /// - **Function calls (custom tools)**: Functions that are defined by you, enabling the model to call your own code.
    ///   Learn more about [function calling](https://platform.openai.com/docs/guides/function-calling).
    public let tools: [Tool]?

    /// An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass.
    /// So 0.1 means only the tokens comprising the top 10% probability mass are considered.
    /// We generally recommend altering this or `temperature` but not both.
    public let topP: Double?

    /// The truncation strategy to use for the model response.
    /// - `auto`: If the context of this response and previous ones exceeds the model's context window size, the model will truncate the response to fit the context window by dropping input items in the middle of the conversation.
    /// - `disabled` (default): If a model response will exceed the context window size for a model, the request will fail with a 400 error.
    public let truncation: String?

    /// Represents token usage details including input tokens, output tokens, a breakdown of output tokens, and the total tokens used.
    public let usage: ResponseUsage?

    /// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
    /// [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).
    public let user: String?

    /// Convenience property that aggregates all `outputText` items from the `output` list.
    /// If no `outputText` content blocks exist, then an empty string is returned.
    public var outputText: String {
        var texts = [String]()
        for item in output {
            if item.type == "message" {
                for content in item.content {
                    if content.type == "output_text" {
                        texts.append(content.text)
                    }
                }
            }
        }
        return texts.joined()
    }

    private enum CodingKeys: String, CodingKey {
        case createdAt = "created_at"
        case error
        case id
        case incompleteDetails = "incomplete_details"
        case instructions
        case maxOutputTokens = "max_output_tokens"
        case metadata
        case model
        case output
        case parallelToolCalls = "parallel_tool_calls"
        case previousResponseId = "previous_response_id"
        case reasoning
        case status
        case text
        case temperature
        case toolChoice = "tool_choice"
        case tools
        case topP = "top_p"
        case truncation
        case usage
        case user
    }
}

extension OpenAIResponse {
    public struct IncompleteDetails: Decodable {
        /// The reason why the response is incomplete.
        let reason: String
    }

    public struct ResponseError: Decodable {
        /// The error code for the response.
        let code: String

        /// A human-readable description of the error.
        let message: String
    }

    /// https://platform.openai.com/docs/api-reference/responses/object#responses/object-output
    public struct ResponseOutputItem: Decodable {
        public let type: String
        public let content: [Content]

        public struct Content: Decodable {
            public let type: String
            public let text: String
        }
    }

    public struct Reasoning: Decodable {
        /// Constrains effort on reasoning for [reasoning models](https://platform.openai.com/docs/guides/reasoning).
        /// Currently supported values are low, medium, and high. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.
        let effort: Effort?

        /// A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process.
        let generateSummary: String?

        private enum CodingKeys: String, CodingKey {
            case effort
            case generateSummary = "generate_summary"
        }
    }

    public enum Status: String, Decodable {
        case completed
        case failed
        case incomplete
        case inProgress = "in_progress"
    }

    public struct ResponseTextConfig: Decodable {
        let format: Format
    }


    /// Represents the literal options: "none", "auto", or "required".
    public enum ToolChoiceOptions: String, Decodable {
        case none = "none"
        case auto = "auto"
        case required = "required"
    }

    /// Represents the tool choice type that indicates which hosted tool to use.
    public struct ToolChoiceTypes: Decodable {
        public let type: ToolType

        public enum ToolType: String, Decodable {
            case fileSearch = "file_search"
            case webSearchPreview = "web_search_preview"
            case computerUsePreview = "computer_use_preview"
            case webSearchPreview2025_03_11 = "web_search_preview_2025_03_11"
        }
    }

    /// Represents a function choice with a name. The type is always "function".
    public struct ToolChoiceFunction: Decodable {
        let name: String
        let type: FunctionType

        enum FunctionType: String, Decodable {
            case function = "function"
        }
    }

    /// A union type for ToolChoice that can be one of:
    /// - A literal option ("none", "auto", "required")
    /// - A tool type (ToolChoiceTypes)
    /// - A function choice (ToolChoiceFunction)
    public enum ToolChoice: Decodable {
        case option(ToolChoiceOptions)
        case types(ToolChoiceTypes)
        case function(ToolChoiceFunction)

        private enum CodingKeys: String, CodingKey {
            case type
        }

        public init(from decoder: Decoder) throws {
            // First try to decode a simple string value.
            let container = try decoder.singleValueContainer()
            if let stringValue = try? container.decode(String.self) {
                if let option = ToolChoiceOptions(rawValue: stringValue) {
                    self = .option(option)
                    return
                } else {
                    throw DecodingError.dataCorruptedError(in: container, debugDescription: "Invalid option: \(stringValue)")
                }
            }

            // Otherwise, decode as an object and inspect the "type" field.
            let keyedContainer = try decoder.container(keyedBy: CodingKeys.self)
            let typeValue = try keyedContainer.decode(String.self, forKey: .type)

            if typeValue == ToolChoiceFunction.FunctionType.function.rawValue {
                let function = try ToolChoiceFunction(from: decoder)
                self = .function(function)
            } else if ["file_search", "web_search_preview", "computer_use_preview", "web_search_preview_2025_03_11"].contains(typeValue) {
                let types = try ToolChoiceTypes(from: decoder)
                self = .types(types)
            } else {
                throw DecodingError.dataCorruptedError(forKey: .type, in: keyedContainer, debugDescription: "Unexpected type value: \(typeValue)")
            }
        }
    }

    // MARK: - ComputerTool

    public struct ComputerTool: Decodable {
        public let displayHeight: Double
        public let displayWidth: Double
        public let environment: Environment
        public let type: ComputerToolType

        public enum Environment: String, Decodable {
            case mac, windows, ubuntu, browser
        }

        public enum ComputerToolType: String, Decodable {
            case computerUsePreview = "computer_use_preview"
        }
    }

    // MARK: - FunctionTool

    public struct FunctionTool: Decodable {
        public let name: String
        public let parameters: [String: AIProxyJSONValue]
        public let strict: Bool
        public let type: FunctionToolType
        public let description: String?

        public enum FunctionToolType: String, Decodable {
            case function = "function"
        }
    }

    // MARK: - UserLocation

    public struct UserLocation: Decodable {
        public let type: UserLocationType
        public let city: String?
        public let country: String?
        public let region: String?
        public let timezone: String?

        public enum UserLocationType: String, Decodable {
            case approximate = "approximate"
        }
    }

    // MARK: - WebSearchTool

    public struct WebSearchTool: Decodable {
        public let type: WebSearchType
        public let searchContextSize: SearchContextSize?
        public let userLocation: UserLocation?

        public enum WebSearchType: String, Decodable {
            case webSearchPreview = "web_search_preview"
            case webSearchPreview2025 = "web_search_preview_2025_03_11"
        }

        public enum SearchContextSize: String, Decodable {
            case low, medium, high
        }
    }

    // MARK: - Filters

    // ComparisonFilter
    public struct ComparisonFilter: Decodable {
        public let key: String
        public let type: ComparisonOperator
        public let value: AIProxyJSONValue

        public enum ComparisonOperator: String, Decodable {
            case eq, ne, gt, gte, lt, lte
        }
    }

    // CompoundFilter – a recursive filter combining an array of filters.
    public struct CompoundFilter: Decodable {
        public let filters: [Filter]
        public let type: CompoundFilterType

        public enum CompoundFilterType: String, Decodable {
            case and, or
        }
    }

    // Filter union: either a ComparisonFilter or a CompoundFilter.
    public enum Filter: Decodable {
        case comparison(ComparisonFilter)
        case compound(CompoundFilter)

        private enum CodingKeys: String, CodingKey {
            case type
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let typeValue = try container.decode(String.self, forKey: .type)
            if typeValue == "and" || typeValue == "or" {
                self = .compound(try CompoundFilter(from: decoder))
            } else if ["eq", "ne", "gt", "gte", "lt", "lte"].contains(typeValue) {
                self = .comparison(try ComparisonFilter(from: decoder))
            } else {
                throw DecodingError.dataCorruptedError(forKey: .type,
                    in: container,
                    debugDescription: "Unknown filter type: \(typeValue)")
            }
        }
    }

    // MARK: - RankingOptions

    public struct RankingOptions: Decodable {
        public let ranker: Ranker?
        public let scoreThreshold: Double?

        public enum Ranker: String, Decodable {
            case auto
            case default20241115 = "default-2024-11-15"
        }
    }

    // MARK: - FileSearchTool

    public struct FileSearchTool: Decodable {
        public let type: FileSearchToolType
        public let vectorStoreIds: [String]
        public let filters: Filter?      // Represents a filter (Comparison or Compound)
        public let maxNumResults: Int?
        public let rankingOptions: RankingOptions?

        public enum FileSearchToolType: String, Decodable {
            case fileSearch = "file_search"
        }
    }

    // MARK: - Tool (Union)

    /// The union type representing one of:
    /// - FileSearchTool
    /// - FunctionTool
    /// - ComputerTool
    /// - WebSearchTool
    public enum Tool: Decodable {
        case fileSearch(FileSearchTool)
        case function(FunctionTool)
        case computer(ComputerTool)
        case webSearch(WebSearchTool)

        enum CodingKeys: String, CodingKey {
            case type
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let typeValue = try container.decode(String.self, forKey: .type)
            switch typeValue {
            case "file_search":
                self = .fileSearch(try FileSearchTool(from: decoder))
            case "function":
                self = .function(try FunctionTool(from: decoder))
            case "computer_use_preview":
                self = .computer(try ComputerTool(from: decoder))
            case "web_search_preview", "web_search_preview_2025_03_11":
                self = .webSearch(try WebSearchTool(from: decoder))
            default:
                throw DecodingError.dataCorruptedError(forKey: .type,
                                                        in: container,
                                                        debugDescription: "Unknown tool type: \(typeValue)")
            }
        }
    }


    public struct OutputTokensDetails: Decodable {
        public let reasoningTokens: Int

        private enum CodingKeys: String, CodingKey {
            case reasoningTokens = "reasoning_tokens"
        }
    }

    public struct ResponseUsage: Decodable {
        public let inputTokens: Int
        public let outputTokens: Int
        public let outputTokensDetails: OutputTokensDetails
        public let totalTokens: Int

        private enum CodingKeys: String, CodingKey {
            case inputTokens = "input_tokens"
            case outputTokens = "output_tokens"
            case outputTokensDetails = "output_tokens_details"
            case totalTokens = "total_tokens"
        }
    }
}


extension OpenAIResponse.Reasoning {
    public enum Effort: String, Decodable {
        case low
        case medium
        case high
    }
}

extension OpenAIResponse.ResponseTextConfig {
    public enum Format: String, Decodable {
        case jsonSchema = "json_schema"
        case text = "text"

        private enum CodingKeys: String, CodingKey {
            case type
        }
        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            let formatValue = try container.decode(String.self, forKey: .type)
            switch formatValue {
            case "json_schema":
                self = .jsonSchema
            case "text":
                self = .text
            default:
                throw DecodingError.dataCorruptedError(
                    forKey: .type,
                    in: container,
                    debugDescription: "Unknown format type: \(formatValue)"
                )
            }
        }
    }
}
