//
//  OpenAIItem.swift
//  AIProxy
//
//  Created by Lou Zell on 12/20/25.
//
// OpenAPI spec: Item, version 2.3.0, line 45079
// Encodable: https://platform.openai.com/docs/api-reference/conversations/create#conversations_create-items-item
// For the corresponding Decodable output, see OpenAIConversationItem.

/// Content item used to generate a response.
/// This is an item sent into the model, and therefore Encodable only.
/// The names are taken from OpenAI's spec, but can they be DRY'd into a single type?
nonisolated public enum OpenAIItem: Encodable, Sendable {
    /// A message input to the model with a role indicating instruction following hierarchy.
    /// Instructions given with the `developer` or` system` role take precedence over instructions given with the `user` role.
    case inputMessage(OpenAIInputMessage)

    /// An output message from the model.
    case outputMessage(OpenAIOutputMessage)

    /// The results of a file search tool call. See the file search guide for more information: https://platform.openai.com/docs/guides/tools-file-search
    case fileSearchToolCall(OpenAIFileSearchToolCall)

    /// A tool call to a computer use tool. See the computer use guide for more information: https://platform.openai.com/docs/guides/tools-computer-use
    case computerToolCall(OpenAIComputerToolCall)

    /// The output of a computer tool call.
    case computerToolCallOutput(OpenAIComputerToolCallOutput)

    /// The results of a web search tool call. See the web search guide for more information: https://platform.openai.com/docs/guides/tools-web-search
    case webSearchToolCall(OpenAIWebSearchToolCall)

    /// A tool call to run a function. See the function calling guide for more information: https://platform.openai.com/docs/guides/function-calling
    case functionToolCall(OpenAIFunctionToolCall)

    /// The output of a function tool call.
    case functionToolCallOutput(OpenAIFunctionToolCallOutput)

    /// A description of the chain of thought used by a reasoning model while generating a response.
    /// Be sure to include these items in your input to the Responses API for subsequent turns of a conversation if you are manually managing context: https://platform.openai.com/docs/guides/conversation-state
    case reasoningItem(OpenAIReasoningItem)

    /// A compaction item generated by the `v1/responses/compact` API.
    case compactionItem(OpenAICompactionItem)

    /// An image generation request made by the model.
    case imageGenerationCall(OpenAIImageGenerationCall)

    /// A tool call to run code.
    case codeInterpreterToolCall(OpenAICodeInterpreterToolCall)

    /// A tool call to run a command on the local shell.
    case localShellCall(OpenAILocalShellCall)

    /// The output of a local shell tool call.
    case localShellCallOutput(OpenAILocalShellCallOutput)

    /// A tool representing a request to execute one or more shell commands.
    case shellToolCall(OpenAIShellToolCall)

    /// The streamed output items emitted by a shell tool call.
    case shellToolCallOutput(OpenAIShellToolCallOutput)

    /// A tool call representing a request to create, delete, or update files using diff patches.
    case applyPatchToolCall(OpenAIApplyPatchToolCall)

    /// The streamed output emitted by an apply patch tool call.
    case applyPatchToolCallOutput(OpenAIApplyPatchToolCallOutput)

    /// A list of tools available on an MCP server.
    case mcpListTools(OpenAIMCPListTools)

    /// A request for human approval of a tool invocation.
    case mcpApprovalRequest(OpenAIMCPApprovalRequest)

    /// A response to an MCP approval request.
    case mcpApprovalResponse(OpenAIMCPApprovalResponse)

    /// An invocation of a tool on an MCP server.
    case mcpToolCall(OpenAIMCPToolCall)

    /// A call to a custom tool created by the model.
    case customToolCall(OpenAICustomToolCall)

    /// The output of a custom tool call from your code, being sent back to the model.
    case customToolCallOutput(OpenAICustomToolCallOutput)
}
