//
//  OpenAIFunctionToolCallResource.swift
//  AIProxy
//
//  Created by Lou Zell on 12/22/25.
//
// OpenAPI spec: FunctionToolCallResource, version 2.3.0, line 9768

/// A tool call to run a function.
///
/// See the [function calling guide](https://platform.openai.com/docs/guides/function-calling) for more information.
nonisolated public struct OpenAIFunctionToolCallResource: Decodable, Sendable {
    /// A JSON string of the arguments to pass to the function.
    public let arguments: String

    /// The unique ID of the function tool call generated by the model.
    public let callID: String

    /// The unique ID of the function tool call.
    public let id: String

    /// The name of the function to run.
    public let name: String

    /// The type of the function tool call. Always `function_call`.
    public let type: String

    /// The status of the item.
    ///
    /// One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    public let status: OpenAIFunctionToolCallStatus?

    private enum CodingKeys: String, CodingKey {
        case arguments
        case callID = "call_id"
        case id
        case name
        case type
        case status
    }
}

/// The status of a function tool call.
nonisolated public enum OpenAIFunctionToolCallStatus: String, Decodable, Sendable {
    case completed
    case inProgress = "in_progress"
    case incomplete
}
