//
//  OpenAICustomToolCallOutputResource.swift
//  AIProxy
//
//  Created by Lou Zell on 12/22/25.
//
// OpenAPI spec: CustomToolCallOutput, version 2.3.0, line 6706

/// The output of a custom tool call from your code, being sent back to the model.
nonisolated public struct OpenAICustomToolCallOutputResource: Decodable, Sendable {
    /// The call ID, used to map this custom tool call output to a custom tool call.
    public let callID: String

    /// The output from the custom tool call generated by your code.
    ///
    /// Can be a string or a list of output content.
    public let output: OpenAICustomToolCallOutputValue

    /// The type of the custom tool call output. Always `custom_tool_call_output`.
    public let type: String

    /// The unique ID of the custom tool call output in the OpenAI platform.
    public let id: String?

    private enum CodingKeys: String, CodingKey {
        case callID = "call_id"
        case output
        case type
        case id
    }
}

/// The output value of a custom tool call.
nonisolated public enum OpenAICustomToolCallOutputValue: Decodable, Sendable {
    case content([OpenAIFunctionToolCallOutputContent])
    case string(String)

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let stringValue = try? container.decode(String.self) {
            self = .string(stringValue)
        } else if let contentArray = try? container.decode([OpenAIFunctionToolCallOutputContent].self) {
            self = .content(contentArray)
        } else {
            throw DecodingError.typeMismatch(
                OpenAICustomToolCallOutputValue.self,
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Expected String or array of output content"
                )
            )
        }
    }
}
