//
//  OpenAILocalShellToolCallOutputResource.swift
//  AIProxy
//
//  Created by Lou Zell on 12/22/25.
//
// OpenAPI spec: LocalShellToolCallOutput, version 2.3.0, line 11857

/// The output of a local shell tool call.
nonisolated public struct OpenAILocalShellToolCallOutputResource: Decodable, Sendable {
    /// The unique ID of the local shell tool call generated by the model.
    public let callID: String

    /// The unique ID of the local shell tool call generated by the model.
    public let id: String

    /// A JSON string of the output of the local shell tool call.
    public let output: String

    /// The type of the local shell tool call output. Always `local_shell_call_output`.
    public let type: String

    /// The status of the item.
    ///
    /// One of `in_progress`, `completed`, or `incomplete`.
    public let status: OpenAILocalShellCallStatus?

    private enum CodingKeys: String, CodingKey {
        case callID = "call_id"
        case id
        case output
        case type
        case status
    }
}
