//
//  OpenAIApplyPatchToolCallResource.swift
//  AIProxy
//
//  Created by Lou Zell on 12/22/25.
//
// OpenAPI spec: ApplyPatchToolCall, version 2.3.0, line 23540

/// A tool call that applies file diffs by creating, deleting, or updating files.
nonisolated public struct OpenAIApplyPatchToolCallResource: Decodable, Sendable {
    /// The unique ID of the apply patch tool call generated by the model.
    public let callID: String

    /// The unique ID of the apply patch tool call. Populated when this item is returned via API.
    public let id: String

    /// One of the create_file, delete_file, or update_file operations applied via apply_patch.
    public let operation: OpenAIApplyPatchOperationResource

    /// The status of the apply patch tool call.
    ///
    /// One of `in_progress` or `completed`.
    public let status: OpenAIApplyPatchCallStatusResource

    /// The type of the item. Always `apply_patch_call`.
    public let type: String

    /// The ID of the entity that created this tool call.
    public let createdBy: String?

    private enum CodingKeys: String, CodingKey {
        case callID = "call_id"
        case id
        case operation
        case status
        case type
        case createdBy = "created_by"
    }
}

/// The status of an apply patch tool call.
nonisolated public enum OpenAIApplyPatchCallStatusResource: String, Decodable, Sendable {
    case completed
    case inProgress = "in_progress"
}

/// An operation applied via apply_patch.
nonisolated public enum OpenAIApplyPatchOperationResource: Decodable, Sendable {
    case createFile(OpenAIApplyPatchCreateFileOperationResource)
    case deleteFile(OpenAIApplyPatchDeleteFileOperationResource)
    case updateFile(OpenAIApplyPatchUpdateFileOperationResource)

    private enum CodingKeys: String, CodingKey {
        case type
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)

        switch type {
        case "create_file":
            self = .createFile(try OpenAIApplyPatchCreateFileOperationResource(from: decoder))
        case "delete_file":
            self = .deleteFile(try OpenAIApplyPatchDeleteFileOperationResource(from: decoder))
        case "update_file":
            self = .updateFile(try OpenAIApplyPatchUpdateFileOperationResource(from: decoder))
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .type,
                in: container,
                debugDescription: "Unknown apply patch operation type: \(type)"
            )
        }
    }
}

/// Instruction describing how to create a file via the apply_patch tool.
nonisolated public struct OpenAIApplyPatchCreateFileOperationResource: Decodable, Sendable {
    /// Diff to apply.
    public let diff: String

    /// Path of the file to create.
    public let path: String

    /// Create a new file with the provided diff.
    public let type: String

    private enum CodingKeys: String, CodingKey {
        case diff
        case path
        case type
    }
}

/// Instruction describing how to delete a file via the apply_patch tool.
nonisolated public struct OpenAIApplyPatchDeleteFileOperationResource: Decodable, Sendable {
    /// Path of the file to delete.
    public let path: String

    /// Delete the specified file.
    public let type: String

    private enum CodingKeys: String, CodingKey {
        case path
        case type
    }
}

/// Instruction describing how to update a file via the apply_patch tool.
nonisolated public struct OpenAIApplyPatchUpdateFileOperationResource: Decodable, Sendable {
    /// Diff to apply.
    public let diff: String

    /// Path of the file to update.
    public let path: String

    /// Update an existing file with the provided diff.
    public let type: String

    private enum CodingKeys: String, CodingKey {
        case diff
        case path
        case type
    }
}
