//
//  OpenAICustomToolCallResource.swift
//  AIProxy
//
//  Created by Lou Zell on 12/22/25.
//
// OpenAPI spec: CustomToolCall, version 2.3.0, line 6672

/// A call to a custom tool created by the model.
nonisolated public struct OpenAICustomToolCallResource: Decodable, Sendable {
    /// An identifier used to map this custom tool call to a tool call output.
    public let callID: String

    /// The input for the custom tool call generated by the model.
    public let input: String

    /// The name of the custom tool being called.
    public let name: String

    /// The type of the custom tool call. Always `custom_tool_call`.
    public let type: String

    /// The unique ID of the custom tool call in the OpenAI platform.
    public let id: String?

    private enum CodingKeys: String, CodingKey {
        case callID = "call_id"
        case input
        case name
        case type
        case id
    }
}
