//
//  OpenAILocalShellToolCallResource.swift
//  AIProxy
//
//  Created by Lou Zell on 12/22/25.
//
// OpenAPI spec: LocalShellToolCall, version 2.3.0, line 11820

/// A tool call to run a command on the local shell.
nonisolated public struct OpenAILocalShellToolCallResource: Decodable, Sendable {
    /// The action to execute.
    public let action: OpenAILocalShellExecAction

    /// The unique ID of the local shell tool call generated by the model.
    public let callID: String

    /// The unique ID of the local shell call.
    public let id: String

    /// The status of the local shell call.
    public let status: OpenAILocalShellCallStatus

    /// The type of the local shell call. Always `local_shell_call`.
    public let type: String

    private enum CodingKeys: String, CodingKey {
        case action
        case callID = "call_id"
        case id
        case status
        case type
    }
}

/// The status of a local shell call.
nonisolated public enum OpenAILocalShellCallStatus: String, Decodable, Sendable {
    case completed
    case inProgress = "in_progress"
    case incomplete
}

/// Execute a shell command on the server.
nonisolated public struct OpenAILocalShellExecAction: Decodable, Sendable {
    /// The command to run.
    public let command: [String]

    /// Environment variables to set for the command.
    public let env: [String: String]

    /// The type of the local shell action. Always `exec`.
    public let type: String

    /// Optional timeout in milliseconds for the command.
    public let timeoutMs: Int?

    /// Optional user to run the command as.
    public let user: String?

    /// Optional working directory to run the command in.
    public let workingDirectory: String?

    private enum CodingKeys: String, CodingKey {
        case command
        case env
        case type
        case timeoutMs = "timeout_ms"
        case user
        case workingDirectory = "working_directory"
    }
}
