//
//  OpenAICodeInterpreterToolCallResource.swift
//  AIProxy
//
//  Created by Lou Zell on 12/22/25.
//
// OpenAPI spec: CodeInterpreterToolCall, version 2.3.0, line 1873

/// A tool call to run code.
nonisolated public struct OpenAICodeInterpreterToolCallResource: Decodable, Sendable {
    /// The code to run, or null if not available.
    public let code: String?

    /// The ID of the container used to run the code.
    public let containerID: String

    /// The unique ID of the code interpreter tool call.
    public let id: String

    /// The outputs generated by the code interpreter, such as logs or images.
    ///
    /// Can be null if no outputs are available.
    public let outputs: [OpenAICodeInterpreterOutputResource]?

    /// The status of the code interpreter tool call.
    ///
    /// Valid values are `in_progress`, `completed`, `incomplete`, `interpreting`, and `failed`.
    public let status: OpenAICodeInterpreterToolCallStatusResource

    /// The type of the code interpreter tool call. Always `code_interpreter_call`.
    public let type: String

    private enum CodingKeys: String, CodingKey {
        case code
        case containerID = "container_id"
        case id
        case outputs
        case status
        case type
    }
}

/// The status of a code interpreter tool call.
nonisolated public enum OpenAICodeInterpreterToolCallStatusResource: String, Decodable, Sendable {
    case completed
    case failed
    case inProgress = "in_progress"
    case incomplete
    case interpreting
}

/// Output from the code interpreter.
nonisolated public enum OpenAICodeInterpreterOutputResource: Decodable, Sendable {
    case image(OpenAICodeInterpreterOutputImageResource)
    case logs(OpenAICodeInterpreterOutputLogsResource)

    private enum CodingKeys: String, CodingKey {
        case type
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)

        switch type {
        case "image":
            self = .image(try OpenAICodeInterpreterOutputImageResource(from: decoder))
        case "logs":
            self = .logs(try OpenAICodeInterpreterOutputLogsResource(from: decoder))
        default:
            throw DecodingError.dataCorruptedError(
                forKey: .type,
                in: container,
                debugDescription: "Unknown code interpreter output type: \(type)"
            )
        }
    }
}

/// The logs output from the code interpreter.
nonisolated public struct OpenAICodeInterpreterOutputLogsResource: Decodable, Sendable {
    /// The logs output from the code interpreter.
    public let logs: String

    /// The type of the output. Always `logs`.
    public let type: String

    private enum CodingKeys: String, CodingKey {
        case logs
        case type
    }
}

/// The image output from the code interpreter.
nonisolated public struct OpenAICodeInterpreterOutputImageResource: Decodable, Sendable {
    /// The type of the output. Always `image`.
    public let type: String

    /// The URL of the image output from the code interpreter.
    public let url: String

    private enum CodingKeys: String, CodingKey {
        case type
        case url
    }
}
