//
//  OpenAICodeInterpreterToolCall.swift
//  AIProxy
//
//  Created by Lou Zell on 12/21/25.
//
// OpenAPI spec: CodeInterpreterToolCall, version 2.3.0, line 35594
// Encodable: https://platform.openai.com/docs/api-reference/conversations/create#conversations_create-items-item-code_interpreter_tool_call
// Decodable: https://platform.openai.com/docs/api-reference/conversations/list-items-object#conversations-list_items_object-data-code_interpreter_tool_call

/// A tool call to run code.
nonisolated public struct OpenAICodeInterpreterToolCall: Codable, Sendable {
    /// The code to run, or null if not available.
    public let code: String

    /// The ID of the container used to run the code.
    public let containerID: String

    /// The unique ID of the code interpreter tool call.
    public let id: String

    /// The outputs generated by the code interpreter, such as logs or images.
    public let outputs: [OpenAICodeInterpreterOutput]

    /// The status of the code interpreter tool call.
    ///
    /// Valid values are `in_progress`, `completed`, `incomplete`, `interpreting`, and `failed`.
    public let status: Status

    /// The type of the code interpreter tool call. Always `code_interpreter_call`.
    public let type = "code_interpreter_call"

    /// Creates a new code interpreter tool call.
    /// - Parameters:
    ///   - code: The code to run, or null if not available.
    ///   - containerID: The ID of the container used to run the code.
    ///   - id: The unique ID of the code interpreter tool call.
    ///   - outputs: The outputs generated by the code interpreter.
    ///   - status: The status of the code interpreter tool call.
    public init(
        code: String,
        containerID: String,
        id: String,
        outputs: [OpenAICodeInterpreterOutput],
        status: Status
    ) {
        self.code = code
        self.containerID = containerID
        self.id = id
        self.outputs = outputs
        self.status = status
    }

    private enum CodingKeys: String, CodingKey {
        case code
        case containerID = "container_id"
        case id
        case outputs
        case status
        case type
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(containerID, forKey: .containerID)
        try container.encode(id, forKey: .id)
        try container.encode(outputs, forKey: .outputs)
        try container.encode(status, forKey: .status)
        try container.encode(type, forKey: .type)
    }
}

extension OpenAICodeInterpreterToolCall {
    /// The status of the code interpreter tool call.
    public enum Status: String, Codable, Sendable {
        case inProgress = "in_progress"
        case completed
        case incomplete
        case interpreting
        case failed
    }
}
