//
//  OpenAIApplyPatchToolCall.swift
//  AIProxy
//
//  Created by Lou Zell on 12/21/25.
//
// OpenAPI spec: ApplyPatchToolCallItemParam, version 2.3.0, line 66171
// Encodable: https://platform.openai.com/docs/api-reference/conversations/create#conversations_create-items-item-apply_patch_tool_call
// Decodable: https://platform.openai.com/docs/api-reference/conversations/list-items-object#conversations-list_items_object-data-apply_patch_tool_call

/// A tool call representing a request to create, delete, or update files using diff patches.
nonisolated public struct OpenAIApplyPatchToolCall: Codable, Sendable {
    /// The unique ID of the apply patch tool call generated by the model.
    public let callID: String

    /// The unique ID of the apply patch tool call. Populated when this item is returned via API.
    public let id: String

    /// The specific create, delete, or update instruction for the `apply_patch` tool call.
    public let operation: OpenAIApplyPatchOperation
    
    /// The status of the apply patch tool call.
    ///
    /// One of `in_progress` or `completed`.
    public let status: Status
    
    /// The type of the item. Always `apply_patch_call`.
    public let type = "apply_patch_call"
    
    /// Creates a new apply patch tool call item parameter.
    /// - Parameters:
    ///   - callID: The unique ID of the apply patch tool call generated by the model.
    ///   - operation: The specific create, delete, or update instruction for the apply_patch tool call.
    ///   - status: The status of the apply patch tool call.
    ///   - id: The unique ID of the apply patch tool call.
    public init(
        callID: String,
        id: String,
        operation: OpenAIApplyPatchOperation,
        status: Status,
    ) {
        self.callID = callID
        self.operation = operation
        self.status = status
        self.id = id
    }
    
    private enum CodingKeys: String, CodingKey {
        case callID = "call_id"
        case operation
        case status
        case type
        case id
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(callID, forKey: .callID)
        try container.encode(operation, forKey: .operation)
        try container.encode(status, forKey: .status)
        try container.encode(type, forKey: .type)
        try container.encode(id, forKey: .id)
    }
}

extension OpenAIApplyPatchToolCall {
    public enum Status: String, Codable, Sendable {
        case inProgress = "in_progress"
        case completed
    }
}
