//
//  OpenAIFunctionToolCall.swift
//  AIProxy
//
//  Created by Lou Zell on 12/21/25.
//
// OpenAPI spec: FunctionToolCall, version 2.3.0, line 43382
// OpenAPI spec: FunctionToolCallResource, version 2.3.0, line 43489
// Encodable: https://platform.openai.com/docs/api-reference/conversations/create#conversations_create-items-item-function_tool_call
// Decodable: https://platform.openai.com/docs/api-reference/conversations/list-items-object#conversations-list_items_object-data-function_tool_call

/// A tool call to run a function.
///
/// See the [function calling guide](https://platform.openai.com/docs/guides/function-calling) for more information.
nonisolated public struct OpenAIFunctionToolCall: Codable, Sendable {
    /// A JSON string of the arguments to pass to the function.
    public let arguments: [String: AIProxyJSONValue]

    /// The unique ID of the function tool call generated by the model.
    public let callID: String
    
    /// The unique ID of the function tool call.
    public let id: String

    /// The name of the function to run.
    public let name: String
    
    /// The type of the function tool call. Always `function_call`.
    public let type = "function_call"
    
    /// The status of the item.
    ///
    /// One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    public let status: Status
    
    /// Creates a new function tool call.
    /// - Parameters:
    ///   - arguments: A JSON string of the arguments to pass to the function.
    ///   - callID: The unique ID of the function tool call generated by the model.
    ///   - name: The name of the function to run.
    ///   - id: The unique ID of the function tool call.
    ///   - status: The status of the item.

    private enum CodingKeys: String, CodingKey {
        case arguments
        case callID = "call_id"
        case name
        case id
        case status
        case type
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(arguments, forKey: .arguments)
        try container.encode(callID, forKey: .callID)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encode(type, forKey: .type)
    }

    public init(
        arguments: [String: AIProxyJSONValue],
        callID: String,
        id: String,
        name: String,
        status: OpenAIFunctionToolCall.Status
    ) {
        self.arguments = arguments
        self.callID = callID
        self.id = id
        self.name = name
        self.status = status
    }
}

extension OpenAIFunctionToolCall {
    /// The status of the function tool call.
    public enum Status: String, Codable, Sendable {
        case inProgress = "in_progress"
        case completed
        case incomplete
    }
}
