//
//  OpenAICustomToolCall.swift
//  AIProxy
//
//  Created by Lou Zell on 12/21/25.
//
// OpenAPI spec: CustomToolCall, version 2.3.0, line 40393
// https://platform.openai.com/docs/api-reference/conversations/create#conversations_create-items-item-custom_tool_call

/// A call to a custom tool created by the model.
nonisolated public struct OpenAICustomToolCall: Encodable, Sendable {
    /// An identifier used to map this custom tool call to a tool call output.
    public let callID: String

    /// The input for the custom tool call generated by the model.
    public let input: String

    /// The name of the custom tool being called.
    public let name: String

    /// The type of the custom tool call. Always `custom_tool_call`.
    public let type = "custom_tool_call"

    /// The unique ID of the custom tool call in the OpenAI platform.
    public let id: String?

    /// Creates a new custom tool call.
    /// - Parameters:
    ///   - callID: An identifier used to map this custom tool call to a tool call output.
    ///   - input: The input for the custom tool call generated by the model.
    ///   - name: The name of the custom tool being called.
    ///   - id: The unique ID of the custom tool call in the OpenAI platform.
    public init(
        callID: String,
        input: String,
        name: String,
        id: String? = nil
    ) {
        self.callID = callID
        self.input = input
        self.name = name
        self.id = id
    }

    private enum CodingKeys: String, CodingKey {
        case callID = "call_id"
        case input
        case name
        case type
        case id
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(callID, forKey: .callID)
        try container.encode(input, forKey: .input)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
    }
}
