//
//  OpenAICustomToolCallOutput.swift
//  AIProxy
//
//  Created by Lou Zell on 12/21/25.
//
// OpenAPI spec: CustomToolCallOutput, version 2.3.0, line 40427
// https://platform.openai.com/docs/api-reference/conversations/create#conversations_create-items-item-custom_tool_call_output

/// The output of a custom tool call from your code, being sent back to the model.
nonisolated public struct OpenAICustomToolCallOutput: Encodable, Sendable {
    /// The call ID, used to map this custom tool call output to a custom tool call.
    public let callID: String

    /// The output from the custom tool call generated by your code.
    ///
    /// Can be a string or a list of output content.
    public let output: Output

    /// The type of the custom tool call output. Always `custom_tool_call_output`.
    public let type = "custom_tool_call_output"

    /// The unique ID of the custom tool call output in the OpenAI platform.
    public let id: String?

    /// Creates a new custom tool call output.
    /// - Parameters:
    ///   - callID: The call ID, used to map this custom tool call output to a custom tool call.
    ///   - output: The output from the custom tool call generated by your code.
    ///   - id: The unique ID of the custom tool call output in the OpenAI platform.
    public init(
        callID: String,
        output: Output,
        id: String? = nil
    ) {
        self.callID = callID
        self.output = output
        self.id = id
    }

    private enum CodingKeys: String, CodingKey {
        case callID = "call_id"
        case output
        case type
        case id
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(callID, forKey: .callID)
        try container.encode(output, forKey: .output)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
    }
}

extension CustomToolCallOutput {
    /// The output from the custom tool call generated by your code.
    nonisolated public enum Output: Encodable, Sendable {
        /// A string of the output of the custom tool call.
        case text(String)

        /// Text, image, or file output of the custom tool call.
        case items([OpenAIOutputContent])

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            switch self {
            case .text(let value):
                try container.encode(value)
            case .items(let items):
                try container.encode(items)
            }
        }
    }
}
