//
//  AnthropicMessage.swift
//  AIProxy
//
//  Created by Lou Zell on 12/10/25.
//

import Foundation

public typealias AnthropicMessageResponseBody = AnthropicMessage

/// Represents Anthropic's `Message` object:
/// https://console.anthropic.com/docs/en/api/messages#message
nonisolated public struct AnthropicMessage: Decodable, Sendable {
    /// Unique object identifier.
    ///
    /// The format and length of IDs may change over time.
    public let id: String

    /// Content generated by the model.
    ///
    /// This is an array of content blocks, each of which has a `type` that determines its shape.
    ///
    /// Example:
    ///
    ///     [{"type": "text", "text": "Hi, I'm Claude."}]
    ///
    /// If the request input `messages` ended with an `assistant` turn, then the response `content`
    /// will continue directly from that last turn. You can use this to constrain the model's output.
    ///
    /// For example, if the input `messages` were:
    ///
    ///     [
    ///       {"role": "user", "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C) Sun"},
    ///       {"role": "assistant", "content": "The best answer is ("}
    ///     ]
    ///
    /// Then the response content might be:
    ///
    ///     [{"type": "text", "text": "B)"}]
    /// 
    public let content: [AnthropicContentBlock]

    /// The model that will complete your prompt.
    /// For additional details and options, see: https://docs.anthropic.com/en/docs/models-overview
    public let model: String

    /// Conversational role of the generated message.
    ///
    /// This will always be `"assistant"`.
    public let role: String

    /// The reason that we stopped.
    ///
    /// This may be one the following values:
    /// * `"end_turn"`: the model reached a natural stopping point
    /// * `"max_tokens"`: we exceeded the requested `max_tokens` or the model's maximum
    /// * `"stop_sequence"`: one of your provided custom `stop_sequences` was generated
    /// * `"tool_use"`: the model invoked one or more tools
    /// * `"pause_turn"`: we paused a long-running turn. You may provide the response back as-is
    ///   in a subsequent request to let the model continue.
    /// * `"refusal"`: when streaming classifiers intervene to handle potential policy violations
    ///
    /// In non-streaming mode this value is always non-null. In streaming mode, it is null in the
    /// `message_start` event and non-null otherwise.
    public let stopReason: AnthropicStopReason?

    /// Which custom stop sequence was generated, if any.
    ///
    /// This value will be a non-null string if one of your custom stop sequences was generated.
    public let stopSequence: String?

    /// Billing and rate-limit usage.
    public let usage: AnthropicUsage

    private enum CodingKeys: String, CodingKey {
        case id
        case content
        case model
        case role
        case stopReason = "stop_reason"
        case stopSequence = "stop_sequence"
        case usage
    }
}

