//
//  MistralTranscriptionRequestBody.swift
//  AIProxy
//
//  Created by Lou Zell on 7/24/26.
//

import Foundation

/// Request body for Mistral's audio transcription endpoint:
/// https://docs.mistral.ai/api/endpoint/audio/transcriptions#operation-audio_api_v1_transcriptions_post
nonisolated public struct MistralTranscriptionRequestBody: MultipartFormEncodable {

    // Required

    /// ID of the model to be used.
    /// Examples: `voxtral-mini-latest`, `voxtral-mini-2507`
    public let model: String

    // Optional

    /// The audio file contents to transcribe.
    /// Provide one of `file`, `fileURL`, or `fileID`.
    public let file: Data?

    /// Filename associated with `file`. Defaults to `aiproxy.m4a` when omitted.
    public let fileName: String?

    /// Content type associated with `file`. Defaults to `audio/mpeg` when omitted.
    public let fileContentType: String?

    /// URL of a file to be transcribed.
    /// Provide one of `file`, `fileURL`, or `fileID`.
    public let fileURL: String?

    /// ID of a file uploaded to `/v1/files`.
    /// Provide one of `file`, `fileURL`, or `fileID`.
    public let fileID: String?

    /// Language of the audio, e.g. `en`. Providing the language can boost accuracy.
    public let language: String?

    /// Sampling temperature.
    public let temperature: Double?

    /// When true, the response includes speaker diarization labels on segments.
    public let diarize: Bool?

    /// Words or phrases that bias the decoder toward expected vocabulary.
    public let contextBias: [String]?

    /// Granularities of timestamps to include in the response.
    public let timestampGranularities: [TimestampGranularity]?

    /// If set to true, Mistral streams transcription events using server-sent events.
    /// Prefer `MistralService.streamingTranscriptionRequest` when consuming streamed transcriptions.
    public var stream: Bool?

    public var formFields: [FormField] {
        var fields: [FormField] = [
            .textField(name: "model", content: self.model),
            self.fileURL.flatMap { .textField(name: "file_url", content: $0) },
            self.fileID.flatMap { .textField(name: "file_id", content: $0) },
            self.language.flatMap { .textField(name: "language", content: $0) },
            self.temperature.flatMap { .textField(name: "temperature", content: String($0)) },
            self.diarize.flatMap { .textField(name: "diarize", content: $0 ? "true" : "false") },
            self.stream.flatMap { .textField(name: "stream", content: $0 ? "true" : "false") },
        ].compactMap { $0 }

        if let file {
            fields.append(
                .fileField(
                    name: "file",
                    content: file,
                    contentType: self.fileContentType ?? "audio/mpeg",
                    filename: self.fileName ?? "aiproxy.m4a"
                )
            )
        }

        if let contextBias {
            for bias in contextBias {
                fields.append(.textField(name: "context_bias", content: bias))
            }
        }

        if let timestampGranularities {
            for granularity in timestampGranularities {
                fields.append(
                    .textField(
                        name: "timestamp_granularities",
                        content: granularity.rawValue
                    )
                )
            }
        }

        return fields
    }

    // This memberwise initializer is autogenerated.
    // To regenerate, use `cmd-shift-a` > Generate Memberwise Initializer
    // To format, place the cursor in the initializer's parameter list and use `ctrl-m`
    public init(
        model: String,
        file: Data? = nil,
        fileName: String? = nil,
        fileContentType: String? = nil,
        fileURL: String? = nil,
        fileID: String? = nil,
        language: String? = nil,
        temperature: Double? = nil,
        diarize: Bool? = nil,
        contextBias: [String]? = nil,
        timestampGranularities: [MistralTranscriptionRequestBody.TimestampGranularity]? = nil,
        stream: Bool? = nil
    ) {
        self.model = model
        self.file = file
        self.fileName = fileName
        self.fileContentType = fileContentType
        self.fileURL = fileURL
        self.fileID = fileID
        self.language = language
        self.temperature = temperature
        self.diarize = diarize
        self.contextBias = contextBias
        self.timestampGranularities = timestampGranularities
        self.stream = stream
    }
}

// MARK: -
extension MistralTranscriptionRequestBody {
    /// Granularities of timestamps to include in the transcription response.
    nonisolated public enum TimestampGranularity: String, Sendable {
        case segment
        case word
    }
}
