//
//  OpenAILocalShellCallOutput.swift
//  AIProxy
//
//  Created by Lou Zell on 12/21/25.
//
// OpenAPI spec: LocalShellToolCallOutput, version 2.3.0, line 45578
// Encodable: https://platform.openai.com/docs/api-reference/conversations/create#conversations_create-items-item-local_shell_call_output
// Decodable: https://platform.openai.com/docs/api-reference/conversations/list-items-object#conversations-list_items_object-data-local_shell_call_output

/// The output of a local shell tool call.
nonisolated public struct OpenAILocalShellToolCallOutput: Codable, Sendable {
    /// The unique ID of the local shell tool call generated by the model.
    public let id: String

    /// A JSON string of the output of the local shell tool call.
    public let output: String

    /// The type of the local shell tool call output. Always `local_shell_call_output`.
    public let type = "local_shell_call_output"

    /// The status of the item.
    ///
    /// One of `in_progress`, `completed`, or `incomplete`.
    public let status: Status?

    /// Creates a new local shell tool call output.
    /// - Parameters:
    ///   - callID: The unique ID of the local shell tool call generated by the model.
    ///   - id: The unique ID of the local shell tool call generated by the model.
    ///   - output: A JSON string of the output of the local shell tool call.
    ///   - status: The status of the item.
    public init(
        id: String,
        output: String,
        status: Status? = nil
    ) {
        self.id = id
        self.output = output
        self.status = status
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case output
        case type
        case status
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(output, forKey: .output)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

extension OpenAILocalShellToolCallOutput {
    /// The status of the local shell tool call output.
    public enum Status: String, Codable, Sendable {
        case inProgress = "in_progress"
        case completed
        case incomplete
    }
}
