//
//  OpenAIFunctionToolCallOutput.swift
//  AIProxy
//
//  Created by Lou Zell on 12/21/25.
//
// OpenAPI spec: FunctionCallOutputItemParam, version 2.3.0, line 65852
// OpenAPI spec: FunctionToolCallOutputResource, version 2.3.0, line 43478
// OpenAPI spec: FunctionToolCallOutput, version 2.3.0, line 43428
// Encodable: https://platform.openai.com/docs/api-reference/conversations/create#conversations_create-items-item-function_tool_call_output
// Decodable: https://platform.openai.com/docs/api-reference/conversations/list-items-object#conversations-list_items_object-data-function_tool_call_output

/// The output of a function tool call.
nonisolated public struct OpenAIFunctionToolCallOutput: Codable, Sendable {
    /// The unique ID of the function tool call output. Populated when this item is returned via API.
    public let id: String

    /// The unique ID of the function tool call generated by the model.
    public let callID: String
    
    /// Text, image, or file output of the function tool call.
    public let output: Output
    
    /// The type of the function tool call output. Always `function_call_output`.
    public let type = "function_call_output"

    /// The status of the item.
    ///
    /// One of `in_progress`, `completed`, or `incomplete`. Populated when items are returned via API.
    public let status: Status

    /// Creates a new function call output item parameter.
    /// - Parameters:
    ///   - callID: The unique ID of the function tool call generated by the model.
    ///   - output: Text, image, or file output of the function tool call.
    ///   - id: The unique ID of the function tool call output.
    ///   - status: The status of the item.
    public init(
        id: String,
        callID: String,
        output: Output,
        status: Status
    ) {
        self.callID = callID
        self.output = output
        self.id = id
        self.status = status
    }
    
    private enum CodingKeys: String, CodingKey {
        case callID = "call_id"
        case output
        case id
        case status
        case type
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(callID, forKey: .callID)
        try container.encode(output, forKey: .output)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encode(type, forKey: .type)
    }
}

extension OpenAIFunctionToolCallOutput {
    // OpenAPI spec: FunctionToolCallOutput#output union, version 2.3.0, line 43450
    /// The output of the function tool call.
    public enum Output: Codable, Sendable {
        /// A JSON string of the output of the function tool call.
        case text(String)

        /// An array of text, image, or file content items.
        case items([OpenAIInputContent])

        case futureProof

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            switch self {
            case .text(let value):
                try container.encode(value)
            case .items(let items):
                try container.encode(items)
            case .futureProof:
                break
            }
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if let stringValue = try? container.decode(String.self) {
                self = .text(stringValue)
            } else if let contentArray = try? container.decode([OpenAIInputContent].self) {
                self = .items(contentArray)
            } else {
                self = .futureProof
                logIf(.error)?.error("AIProxy: Could not decode OpenAIFunctionToolCallOutput.Output. Expected String or array of output content")
            }
        }
    }
}

extension OpenAIFunctionToolCallOutput {
    /// The status of the function tool call.
    public enum Status: String, Codable, Sendable {
        case inProgress = "in_progress"
        case completed
        case incomplete
    }
}
