//
//  OpenAILocalShellCall.swift
//  AIProxy
//
//  Created by Lou Zell on 12/21/25.
//
// OpenAPI spec: LocalShellToolCall, version 2.3.0, line 45541
// Encodable: https://platform.openai.com/docs/api-reference/conversations/create#conversations_create-items-item-local_shell_call
// Decodable: https://platform.openai.com/docs/api-reference/conversations/list-items-object#conversations-list_items_object-data-local_shell_call

/// A tool call to run a command on the local shell.
nonisolated public struct OpenAILocalShellToolCall: Codable, Sendable {
    /// The action to execute on the local shell.
    public let action: OpenAILocalShellToolCallAction
    
    /// The unique ID of the local shell tool call generated by the model.
    public let callID: String
    
    /// The unique ID of the local shell call.
    public let id: String
    
    /// The status of the local shell call.
    public let status: Status
    
    /// The type of the local shell call. Always `local_shell_call`.
    public let type = "local_shell_call"
    
    /// Creates a new local shell tool call.
    /// - Parameters:
    ///   - action: The action to execute on the local shell.
    ///   - callID: The unique ID of the local shell tool call generated by the model.
    ///   - id: The unique ID of the local shell call.
    ///   - status: The status of the local shell call.
    public init(
        action: OpenAILocalShellToolCallAction,
        callID: String,
        id: String,
        status: Status
    ) {
        self.action = action
        self.callID = callID
        self.id = id
        self.status = status
    }
    
    private enum CodingKeys: String, CodingKey {
        case action
        case callID = "call_id"
        case id
        case status
        case type
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(callID, forKey: .callID)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encode(type, forKey: .type)
    }
}

extension OpenAILocalShellToolCall {
    /// The status of the local shell call.
    public enum Status: String, Codable, Sendable {
        case inProgress = "in_progress"
        case completed
        case incomplete
    }
}
