//
//  ReplicateFluxControlNetInputSchema.swift
//
//
//  Created by Lou Zell on 10/6/24.
//

import Foundation

/// https://replicate.com/xlabs-ai/flux-controlnet/api/schema
public struct ReplicateFluxControlNetInputSchema: Encodable {
    // Required

    /// Input image
    public let image: URL

    /// Input prompt
    public let prompt: String

    // Optional

    /// Default: 3.5
    /// The CFG (Classifier Free Guidance)
    public let cfg: Double?

    /// Number of inference steps
    /// Default: 28
    public let numInferenceSteps: Int?

    /// Random seed
    public let seed: Int?

    private enum CodingKeys: String, CodingKey {
        case cfg
        case image
        case numInferenceSteps = "num_inference_steps"
        case prompt
        case seed
    }

    // This memberwise initializer is autogenerated.
    // To regenerate, use `cmd-shift-a` > Generate Memberwise Initializer
    // To format, place the cursor in the initializer's parameter list and use `ctrl-m`
    public init(
        image: URL,
        prompt: String,
        cfg: Double? = nil,
        numInferenceSteps: Int? = nil,
        seed: Int? = nil
    ) {
        self.image = image
        self.prompt = prompt
        self.cfg = cfg
        self.numInferenceSteps = numInferenceSteps
        self.seed = seed
    }
}
