//
//  ReplicateFluxSchnellInputSchema.swift
//
//
//  Created by Lou Zell on 8/28/24.
//

import Foundation

/// Input schema for use with requests to Black Forest Lab's Flux Schnell model:
/// https://replicate.com/black-forest-labs/flux-schnell/api/schema#input-schema
nonisolated public struct ReplicateFluxSchnellInputSchema: Encodable, Sendable {
    // Required

    /// Prompt for generated image
    public let prompt: String

    // Optional

    /// Aspect ratio for the generated image
    /// Valid ratios are: `1:1`, `16:9`, `21:9`, `2:3`, `3:2`, `4:5`, `5:4`, `9:16`, `9:21`
    public let aspectRatio: String?

    /// Disable safety checker for generated images.
    public let disableSafetyChecker: Bool?

    /// Run faster predictions with model optimized for speed (currently fp8 quantized); disable to run in original bf16
    /// Defaults to `true`
    public let goFast: Bool?

    /// Number of outputs to generate
    public let numOutputs: Int?

    /// Format of the output images
    public let outputFormat: OutputFormat?

    /// Quality when saving the output images, from 0 to 100. 100 is best quality, 0 is lowest quality.
    /// Not relevant for .png outputs
    public let outputQuality: Int?

    /// Random seed. Set for reproducible generation
    public let seed: Int?

    private enum CodingKeys: String, CodingKey {
        case aspectRatio = "aspect_ratio"
        case disableSafetyChecker = "disable_safety_checker"
        case goFast = "go_fast"
        case numOutputs = "num_outputs"
        case outputFormat = "output_format"
        case outputQuality = "output_quality"
        case prompt
        case seed
    }

    // This memberwise initializer is autogenerated.
    // To regenerate, use `cmd-shift-a` > Generate Memberwise Initializer
    // To format, place the cursor in the initializer's parameter list and use `ctrl-m`
    public init(
        prompt: String,
        aspectRatio: String? = nil,
        disableSafetyChecker: Bool? = nil,
        goFast: Bool? = nil,
        numOutputs: Int? = nil,
        outputFormat: ReplicateFluxSchnellInputSchema.OutputFormat? = nil,
        outputQuality: Int? = nil,
        seed: Int? = nil
    ) {
        self.prompt = prompt
        self.aspectRatio = aspectRatio
        self.disableSafetyChecker = disableSafetyChecker
        self.goFast = goFast
        self.numOutputs = numOutputs
        self.outputFormat = outputFormat
        self.outputQuality = outputQuality
        self.seed = seed
    }
}

// MARK: - InputSchema.OutputFormat
extension ReplicateFluxSchnellInputSchema {
    nonisolated public enum OutputFormat: String, Encodable, Sendable {
        case jpg
        case png
        case webp
    }
}
