//
//  AnthropicToolUnion.swift
//  AIProxy
//
//  Created by Lou Zell on 12/10/25.
//

import Foundation

/// Definitions of tools that the model may use.
///
/// If you include `tools` in your API request, the model may return `tool_use` content blocks that represent the model's use of those tools.
/// You can then run those tools using the tool input generated by the model and then optionally return results back to the model using `tool_result` content blocks.
///
/// There are two types of tools: client tools and server tools. The behavior described below applies to client tools.
/// For server tools, see their individual documentation as each has its own behavior (e.g., the web search tool).
///
/// Each tool definition includes:
///
/// - `name`: Name of the tool.
/// - `description`: Optional, but strongly-recommended description of the tool.
/// - `input_schema`: JSON schema for the tool input shape that the model will produce in `tool_use` output content blocks
///   * The JSON schema spec is available here: https://json-schema.org/draft/2020-12
///
/// For example, if you defined `tools` as:
///
///     [
///       {
///         "name": "get_stock_price",
///         "description": "Get the current stock price for a given ticker symbol.",
///         "input_schema": {
///           "type": "object",
///           "properties": {
///             "ticker": {
///               "type": "string",
///               "description": "The stock ticker symbol, e.g. AAPL for Apple Inc."
///             }
///           },
///           "required": ["ticker"]
///         }
///       }
///     ]
///
/// And then asked the model "What's the S&P 500 at today?", the model might produce `tool_use` content blocks in the response like this:
///
///     [
///       {
///         "type": "tool_use",
///         "id": "toolu_01D7FLrfh4GYq7yT1ULFeyMV",
///         "name": "get_stock_price",
///         "input": { "ticker": "^GSPC" }
///       }
///     ]
///
/// You might then run your `get_stock_price` tool with `{"ticker": "^GSPC"}` as an input,
/// and return the following back to the model in a subsequent `user` message:
///
///     [
///       {
///         "type": "tool_result",
///         "tool_use_id": "toolu_01D7FLrfh4GYq7yT1ULFeyMV",
///         "content": "259.75 USD"
///       }
///     ]
///
/// Tools can be used for workflows that include running client-side tools and functions,
/// or more generally whenever you want the model to produce a particular JSON structure of output.
///
/// See our guide for more details: https://docs.claude.com/en/docs/tool-use
///
/// Represents Anthropic's `ToolUnion` object:
/// https://console.anthropic.com/docs/en/api/messages#tool_union
nonisolated public enum AnthropicToolUnion: Encodable, Sendable {
    /// A custom client tool.
    case customTool(AnthropicTool)

    /// Bash tool (version 2025-01-24).
    case bashTool20250124(AnthropicToolBash20250124)

    /// Text editor tool (version 2025-01-24).
    case textEditorTool20250124(AnthropicToolTextEditor20250124)

    /// Text editor tool (version 2025-04-29).
    case textEditorTool20250429(AnthropicToolTextEditor20250429)

    /// Text editor tool (version 2025-07-28).
    case textEditorTool20250728(AnthropicToolTextEditor20250728)

    /// Web search tool (version 2025-03-05).
    case webSearchTool20250305(AnthropicWebSearchTool20250305)

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .customTool(let tool):
            try tool.encode(to: encoder)
        case .bashTool20250124(let tool):
            try tool.encode(to: encoder)
        case .textEditorTool20250124(let tool):
            try tool.encode(to: encoder)
        case .textEditorTool20250429(let tool):
            try tool.encode(to: encoder)
        case .textEditorTool20250728(let tool):
            try tool.encode(to: encoder)
        case .webSearchTool20250305(let tool):
            try tool.encode(to: encoder)
        }
    }

    /// For call site backwards-compatibility with SDK versions <= "0.134.0".
    public init(
        description: String,
        inputSchema: [String: AIProxyJSONValue],
        name: String,
        cacheControl: AnthropicCacheControlEphemeral? = nil
    ) {
        self = .customTool(
            AnthropicTool(
                description: description,
                inputSchema: inputSchema,
                name: name,
                cacheControl: cacheControl,
            )
        )
    }
}
