//
//  OpenAIConversationsInputItem.swift
//
//
//  Created by Lou Zell on 12/19/24.
//
// OpenAPI spec: InputItem, version 2.3.0, line 44810
// https://platform.openai.com/docs/api-reference/conversations/create#conversations_create-items

import Foundation

/// An input item that can be added to a conversation.
nonisolated public enum OpenAIInputItem: Encodable, Sendable {
    /// An item representing part of the context for the response to be generated by the model.
    /// Can contain text, images, and audio inputs, as well as previous assistant responses and tool call
    case item(OpenAIItem)

    /// An internal identifier for an item to reference.
    case itemReference(OpenAIItemReference)

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .item(let item):
            try item.encode(to: encoder)
        case .itemReference(let itemReference):
            try itemReference.encode(to: encoder)
        }
    }
}
