//
//  OpenAIConversationsInputItem.swift
//
//
//  Created by Lou Zell on 12/19/24.
//
// OpenAPI spec: InputItem, version 2.3.0, line 44810
// https://platform.openai.com/docs/api-reference/conversations/create#conversations_create-items

import Foundation

/// An input item that can be added to a conversation.
nonisolated public enum OpenAIInputItem: Encodable, Sendable {
    /// A message input to the model with a role indicating instruction following hierarchy.
    /// Instructions given with the `developer` or `system` role take precedence over instructions given with the `user` role.
    /// Messages with the `assistant` role are presumed to have been generated by the model in previous interactions.
    case inputMessage(OpenAIEasyInputMessage)

    /// An item representing part of the context for the response to be generated by the model.
    /// Can contain text, images, and audio inputs, as well as previous assistant responses and tool call
    case item(OpenAIItem)

    /// An internal identifier for an item to reference.
    case itemReference(OpenAIItemReference)

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .inputMessage(let ezMessage):
            try ezMessage.encode(to: encoder)
        case .item(let item):
            try item.encode(to: encoder)
        case .itemReference(let itemReference):
            try itemReference.encode(to: encoder)
        }
    }
}
